language: java
install: true
os: linux
dist: xenial

jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "atcmasta"

script:
  - mvn clean install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
