language: java
sudo: false
install: true

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "atcmasta"

script:
  - mvn clean install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
